on: [workflow_dispatch]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CREATE_APP_TOKEN_APP_ID }}
          private-key: ${{ secrets.CREATE_APP_TOKEN_PRIVATE_KEY }}
      - name: Output token
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "Created Access Token: ${TOKEN:4}"